language: cpp
compiler:
  - clang
before_script:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.48-dev libsdl2-dev libsdl2-mixer-dev libpixman-1-dev
  - git clone --branch dummy "https://github.com/take-cheeze/RTP.git" $RPG_RTP_PATH
  - CXX="$CXX $WORKAROUND_CXX_FLAGS" cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .
script:
  - make -j2
  - make test
after_script:
  - cat lib/TestGame/TestGame-2000/easyrpg_log.txt
  - cat Testing/Temporary/LastTest.log
env:
  global:
    - WORKAROUND_CXX_FLAGS="-DBOOST_NO_CXX11_SMART_PTR -DBOOST_NO_CXX11_HDR_ARRAY -DBOOST_NO_RTTI -DBOOST_NO_TYPEID"
    - RPG_RTP_PATH="./lib/RTP"
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG
    - CMAKE_BUILD_TYPE=RELEASE
